=== api-evangelist/oura/json-schema/oura-publicdailyreadiness.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/api-evangelist/oura/main/json-schema/oura-publicdailyreadiness.json",
  "title": "PublicDailyReadiness",
  "description": "Public object defining daily readiness.",
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1,
      "title": "",
      "description": "Unique identifier of the object."
    },
    "contributors": {
      "$ref": "#/components/schemas/PublicReadinessContributors",
      "title": "",
      "description": "Contributors of the daily readiness score."
    },
    "day": {
      "$ref": "#/components/schemas/ISODate",
      "title": "",
      "description": "Day that the daily readiness belongs to."
    },
    "score": {
      "type": "integer",
      "nullable": true,
      "title": "",
      "description": "Daily readiness score."
    },
    "temperature_deviation": {
      "type": "number",
      "nullable": true,
      "title": "",
      "description": "Temperature deviation in degrees Celsius."
    },
    "temperature_trend_deviation": {
      "type": "number",
      "nullable": true,
      "title": "",
      "description": "Temperature trend deviation in degrees Celsius."
    },
    "timestamp": {
      "$ref": "#/components/schemas/LocalizedDateTime",
      "title": "",
      "description": "Timestamp of the daily readiness."
    }
  },
  "type": "object",
  "required": [
    "id",
    "contributors",
    "day",
    "timestamp"
  ],
  "x-cloud-only": true,
  "x-collection": "publicdailyreadiness",
  "x-owner": "wellbeing-squad"
}

=== api-evangelist/oura/examples/oura-publicdailyreadiness-example.json
{
  "id": "string",
  "contributors": {
    "activity_balance": 0,
    "body_temperature": 0,
    "hrv_balance": 0,
    "previous_day_activity": 0,
    "previous_night": 0,
    "recovery_index": 0,
    "resting_heart_rate": 0,
    "sleep_balance": 0,
    "sleep_regularity": 0
  },
  "day": "string",
  "score": 0,
  "temperature_deviation": 0.0,
  "temperature_trend_deviation": 0.0,
  "timestamp": "string"
}
